name: dukkantek_task
description: Dukkantek Task project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  connectivity:
  bloc:
  flutter_bloc:
  path:
  equatable:
  http:
  flutter_localizations:
    sdk: flutter
  flutter_screenutil:
  local_auth:
  json_annotation:
  fluttertoast: ^8.0.9

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3
  analyzer: ^3.3.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    - family: light
      fonts:
        - asset: assets/fonts/titillium_light.otf

    - family: regular
      fonts:
        - asset: assets/fonts/titillium_regular.otf

    - family: bold
      fonts:
        - asset: assets/fonts/titillium_bold.otf

    - family: simiBold
      fonts:
        - asset: assets/fonts/titilliumweb_semiBold.ttf


flutter_intl:
  enabled: true
